### ISSUE TITLE
🏗️Create application layer for domain logic

### ISSUE THREAD

**Issue by MayugeStudio** [MayugeStudio/rabbit-todo-python#10]
## Purpose
To separate the domain logic from the command-line interface, making the codebase more maintainable and testable. 
This layer will contain the core business rules and operations, which will be invoked by the command-line commands. 

## Tasks
- [ ] Create application layer directory.
- [ ] Create Add-Task-Use-Case.
- [ ] Create Remove-Task-Use-Case.
- [ ] Create Done-Task-Use-Case.
- [ ] Create List-Task-Use-Case.
- [ ] Write Tests.
