### ISSUE TITLE
🏗️Refactor output methods with Interface

### ISSUE THREAD

**Issue by MayugeStudio** [MayugeStudio/rabbit-todo-python#11]
## Purpose
Create an interface for output and aim to split the output and domain processing.

## Tasks
- [ ] Create an Interface for output.
- [ ] Create a class for the CLI that implements this interface. 
- [ ] Write tests for the implemented class.
