### ISSUE TITLE
✨Implement Graphical Progress Display for Milestone.

### ISSUE THREAD

**Issue by MayugeStudio** [MayugeStudio/rabbit-todo-python#36]
## Purpose
Visualization makes it easier for users to check the progress of their tasks.

## Tasks
- [ ] Create interface for displaying progress 
- [ ] Implement Graphical Progress Bar Class 
- [ ] DI to use the class for display.
