### ISSUE TITLE
✨Implement Graphical Progress Display for Feature

### ISSUE THREAD

**Issue by MayugeStudio** [MayugeStudio/rabbit-todo-python#37]
## Purpose
To make it easier to check progress by visualizing progress.

## Tasks
- [ ] Create interface for displaying progress
- [ ] Implement Graphical Progress Bar Class
- [ ] DI to use the class for display.
